name: Test
on: 
  # push:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch: 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a One-Liner Script
        run: sleep 5

      - name: Run a Multi-Line Script
        run: |
          echo "Add other actions to build, "
          echo "test, and deploy your project"
          
