name: upper-build
on:
    push:
        paths: 
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: #Manual

jobs:
    build:
        name: Build 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Go Version
              run: go version

            - name: Install GO
              uses: actions/setup-go@v5
              with:
                #go-version: '1.22'
                go-version-file: ./upper/go.mod
                cache-dependency-path: ./upper/go.sum

            - name: Go Version
              run: go version

            - name: Dependencies Download
              run: go mod download
        