name: upper-build
on:
    push:
        paths: 
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: #Manual

jobs:
    build:
        name: Build 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Go Version
              run: go version
        